### ISSUE TITLE
USER STORY: Admin - Review and Edit User-Submitted Posts

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#14]
_As a_ **Site Administrator**, _I can_ **review and edit user-submitted posts** _so that I can_ **ensure content quality and appropriateness**.

#### Acceptance Criteria:
- Admin can post, review, edit or delete own posts as well as users.
- Admin can access a list of all user-submitted posts.
- Admin can review, approve, or reject submissions.
- Admin can edit the content of the posts for clarity, grammar, or appropriateness.

#### Tasks:
- [x] Set up the admin panel and create, read, update and delete posts. 
- [x] Develop a system in the admin interface to list all user-submitted posts.
- [x] Create options for approving, rejecting, or editing these posts.
- [x] Test the post review and editing process.
