### ISSUE TITLE
[TASK]: Set Up Development Environment

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#21]
#### Tasks:
- [x] Set up IDE and configure settings
- [x] Create and activate a virtual environment
- [x] Install necessary packages and dependencies
