### ISSUE TITLE
[TASK]: Set Up Database Connection 

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#22]
#### Tasks:
- [x] Set up ElephantSQL
- [x] Configure database connection in the Django settings
- [x] Test database connection to ensure proper setup
