### ISSUE TITLE
[TASK]:  Setup Heroku Deployment

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#23]
#### Tasks:
- [x] Configure environment variables on Heroku
- [x] Set up deployment method (GitHub integration or Heroku CLI)
- [x] Perform an initial deployment to test setup
