### ISSUE TITLE
[TASK]: Documentation - Update/Final check

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#24]
#### Tasks:

- [x] Create a basic structure for the README

- [x] Regularly update README with project progress
- [x] Ensure clarity and comprehensiveness of documentation
- [x] Ensure all features and functionalities are well-documented
- [x] Conduct a thorough review of all documentation
- [x] Update any outdated or incomplete sections
