### ISSUE TITLE
[TASK]: Testing & Validation

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#25]
#### Tasks:
- [x] Validate all functionalities against user stories
- [x] Define manual and automated test cases.
- [x] Test all features of the webpage.
- [x] Perform accessibility checks using WAVE Web Accessibility Evaluation Tool.
- [x] Validate HTML using W3C Markup Validation Service.
- [x] Validate CSS using W3C's CSS Validation Service.
- [x] Conduct Lighthouse audits to assess performance, accessibility, progressive web apps, SEO, and best practices.
- [x] Use CI Python Linter for Python code quality checks.
- [x] Document all implemented testing in README.
