### ISSUE TITLE
[TASK]: FINAL DEPLOYMENT

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#26]
#### Tasks:
- [x] Deploy the initial version of the application to Heroku
- [x] Test key functionalities in the deployed version
- [x] Fix any deployment-specific issues
- [x] Verify that all features work as expected in the final deployment
- [x] Ensure `DEBUG = False` is set in settings.py
- [x] Remove any hardcoded sensitive information
- [x] Conduct a final deployment to Heroku
- [x] Document the deployment process in README
