### ISSUE TITLE
USER STORY: Bookmark Blog Posts

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#29]
_As a_ **registered user**, _I can_ **bookmark blog posts** _so that I can_ **easily access them later**.

#### Acceptance Criteria:
- [x] Users can bookmark a post from the detail page.
- [x] Users can view their list of bookmarked posts in a separete page.
- [x] Users receive visual confirmation when a blog post is bookmarked or removed as bookmarked.
- [x] The 'Bookmarked Posts' list is persistent and retrievable upon subsequent logins.

#### Tasks:
- [x] Implement a 'bookmark' feature in the blogpost model using a ManyToMany field with the User model.
- [x] Create a view and template that allow users to toggle posts as bookmarked.
- [x] Ensure the functionality is tested and stable.
