### ISSUE TITLE
USER STORY: Receive Validating Messages

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#37]
### Description:

_As a_ **user** _I can_ **receive validating messages** _so that I can_ **feel safe my actions are executed the right way**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Users receive a confirmation message after successful login/logout.
- **Acceptance Criteria 2:** Users are shown an error message for login/logout failures.
- **Acceptance Criteria 3:** Users get feedback messages following successful CRUD actions.
- **Acceptance Criteria 4:** Users receive validation messages for form input errors.

### Tasks:
- [x] Set up bootstrap alerts using messages in Django
- [x] Create alert/messages for logging in/out of the site.
- [x] Create validating messages for CRUD - actions
- [x] Create input validations throughout the site.
