### ISSUE TITLE
USER STORY: Create, Update & Delete User Profile

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#4]
- **Description:**
  _As a_ **user**, _I can_ **create and edit my profile, add/change profile picture or delete the account** _so that I can_ **personalize my profile and share more about myself with the community, unless i want to delete the account**.

- **Acceptance Criteria:**
  - Users can access and edit their profile information.
  - Users can upload, change, or remove their profile picture.
  - Changes to the profile should be saved and reflected immediately.
  - The interface for editing the profile and uploading a picture should be user-friendly.
  - Be able to delete the whole account .

- **Tasks:**
  - [x] Create or update a model to store user profile and profile picture.
  - [x] Develop a form for editing all profile fields and uploading a profile picture.
  - [x] Implement views and templates for the edit profile feature.
  - [x] Implement views and templates for the delete profile feature.
  - [x] Write backend logic for handling updates and picture uploads.
  - [x] Ensure uploaded images are stored and served correctly.
  - [x] Test the functionality of editing profile and changing the picture.
  - [x] Write backend logic for handling account to be deleted.
