### ISSUE TITLE
USER STORY: Receive Page Error Messages

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/Culture-Club#42]
### Description:

_As a_ **user**, _I want to_ **be directed to a custom error page if something isn't working correctly**, _so that_ **I feel informed and can easily navigate back to the main site**.

### Acceptance Criteria:
- **Acceptance Criteria 1:** Users are redirected to a custom 403, 404, 405 and 500 page if any errors occur.
- **Acceptance Criteria 2:** The error page clearly indicates that the requested page could not be found or other error messages.
- **Acceptance Criteria 3:** The error page provides a link or button to return to the home page.

### Tasks:
- [x] Design and implement a custom 403, 404, 405 and 500  error pages.
- [x] Ensure thepages includes a clear message indicating what's wrong.
- [x] Add a link or button on the page to redirect users to the home page.
- [x] Configure the web application to display the custom pages for all errors.
